# Generated by Django 5.1.4 on 2024-12-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_degree_course_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='degree',
        ),
        migrations.DeleteModel(
            name='Degree',
        ),
    ]
