# Generated by Django 5.1.4 on 2024-12-07 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
    ]
